baseURL = 'https://qenya.tel/'
languageCode = 'en-GB'
title = 'qenya'

[params]
description = "A work in progress. Don't @ me please"

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30